import daisyui from "daisyui";
import {
  IndoGithubers, 
  PengelolaanBuku,
  GrensaStiker,
  Qovier,
  Nyatet,
  Ceritain,
  Forestapi,
  Fresh4u,
  IamRifai,
  Instafam,
  Khaidar,
  Luminous,
  Ngajax,
  Railway,
  SmartCulture,
  Weekly,
  Pandev,
  Yazzlink,
  Klass,
  css,
  disyui,
  framer,
  html,
  js,
  laravel,
  livewire,
  mongodb,
  nextjs,
  nodejs,
  nuxtjs,
  pnpm,
  postgresql,
  prisma,
  reactjs,
  redux,
  swiper,
  vite,
  tailwind,
  vitest,
  zustand,
  firebase,
  flask,
  bootstrap,
  nestjs
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Showcase",
    link: "/showcase",
  },
  // {
  //   _id: 1002,
  //   title: "Shop",
  //   link: "/shop",
  // },
];
// =================== NavBarList End here ======================


// =================== NavBarList Start here ====================
export const ShowCaseList = [
  {
    id: 0,
    img: IndoGithubers,
    name: "IndoGitHubers!",
    user: "depa",
    description: "Halo semuanya, salam kenal 👋 perkenalkan saya depa. izin ikutan showcase project sederhana yg saya bikin 🙇‍♂️ project ini dibikin karena rasa penasaran saya soal siapa github user di indonesia yg paling banyak followers & contributions nya. sambil belajar react & biar ada hasilnya, saya coba bikin project ini dengan nama IndoGitHubers *dan ternyata rank 1 nya Pak Dhika 🥇",
    techStack: ["React JS", "Tailwind CSS"],
    imgStack: [reactjs, tailwind],
    githubRepo: "https://github.com/depapp/IndoGitHubers",
    linkWeb: "https://indogithubers.vercel.app/",
    like: 0,
  },
  {
    id: 1,
    img: PengelolaanBuku,
    name: "Pengelolaan Buku",
    user: "Kang Dappa",
    description: "Assalammulaikum pak dika dan teman teman saya mau showcase 2 project sederhana dan kecil kecilan saja btw project ini tugas akhir kelas DICODING daripada nganggur di lokal mending saya push ke production dan saya submit biar temen temen dan pak dika dapat mencoba project yang sudah saya buat ini . mohon maaf sebelumnya project ini belum responsif ( baru buat ui versi desktop )",
    techStack: ["Html", "Css", "Javascript"],
    imgStack: [html, css, js],
    githubRepo: "https://github.com/siidappa/pengelolaan-buku",
    linkWeb: "https://pengelolaan-buku.vercel.app",
    like: 0,
  },
  {
    id: 2,
    img: Qovier,
    name: "Qovier",
    user: "cholis04",
    description: "Halo Pak Dhika dan halo juga teman-teman member WPU, izinkan saya memperkenalkan personal project yang telah saya kerjakan dalam beberapa minggu ini, yang saya kasih nama Qovier. Namanya sendiri diambil dari 'Color Pairs', kemudian disingkat jadi 'Co-Pair', dan akhirnya sedikit diplesetkan menjadi Qovier. Tentang Project ini adalah sebuah online generator tool untuk berkesperimen dan menjelajahi pasangan warna. Qovier akan menghasilkan daftar pasangan warna (kombinasi dua warna) dalam bentuk solid, teks, pola, warna gradasi dan juga ilustrasi (flatline). Gas langsung cek aja",
    techStack: ["Next js", "Tailwind css", "Swipper js", "Framer motion"],
    imgStack: [nextjs, tailwind, swiper, framer],
    githubRepo: "https://github.com/PILIPSCODE/Grensa-Stiker",
    linkWeb: "https://grensa-stiker.vercel.app/",
    like: 0,
  },
  {
    id: 3,
    img: GrensaStiker,
    name: "Grensa Stiker",
    user: "Kang Error",
    description: "hallo teman teman WPU dan Pak Sandi, Saya mau memamerkan Portfolio teman saya, yang saya buat Portfolionya untuk Tambah2 Project untuk Portfolio saya",
    techStack: ["Next js", "Tailwind css", "Swipper js", "Framer motion"],
    imgStack: [nextjs, tailwind, swiper, framer],
    githubRepo: "https://github.com/PILIPSCODE/Grensa-Stiker",
    linkWeb: "https://grensa-stiker.vercel.app/",
    like: 0,
  },
    // data baru

  {
    id: 4,
    img: Pandev,
    name: "Nyatet",
    user: "zekkeN",
    description: "Terima kasih, Pak Dhika, dan komunitas Discord. Data todo list dan note dienkripsi dengan aman menggunakan enkripsi bawaan Laravel. Terima kasih kepada @antwa atas kontribusinya. Terbuka untuk kritik dan saran. Fitur: Login & Register, Login dengan GitHub / Google, Reset Password (dikirim via email), Todo List, Note (dapat dikunci), Enkripsi Laravel menggunakan OpenSSL (AES-256 dan AES-128). 🙏",
    techStack: ["Laravel 10", "Tailwind CSS", "Livewire", "Daisy UI"],
    imgStack: [laravel, tailwind, livewire, disyui],
    githubRepo: "https://github.com/orz14/nyatet-app",
    linkWeb: "https://nyatet.orzproject.my.id/",
    like: 0,
  },
  {
    id: 5,
    img: Yazzlink,
    name: "Yazzlink",
    user: "yazz",
    description: "Assalamualaikum! Saya Muhammad Yazid Akbar. Ini showcase pertama saya. Saya belajar Firebase dan mengaplikasikannya dalam proyek website mirip Linktr.ee. Menggunakan Next.js, Firebase, Tailwind CSS, dan Ant Design. Fitur termasuk menambah link, mengedit tampilan, dan pelacakan pengunjung secara real-time.",
    techStack: ["Next js", "Firebase", "Tailwind CSS"],
    imgStack: [nextjs, firebase, livewire, disyui],
    githubRepo: "https://github.com/yazz803/linker_sosmed",
    linkWeb: "https://yazzlink.vercel.app/",
    like: 0,
  },
  {
    id: 6,
    img: Ceritain,
    name: "Ceritain",
    user: "CicakUngu",
    description: "Assalamualaikum, saya Rijal, showcase ke-2. Saya membuat website 'Ceritain' untuk berbagi cerita, keluh kesah, dan lebih. Website masih dalam pengembangan, mungkin ada beberapa bug. Terima kasih! 👋",
    techStack: ["Nuxt JS", "Tailwind CSS", "PostgreSQL",],
    imgStack: [nuxtjs, tailwind, postgresql, nodejs],
    githubRepo: "https://github.com/euxzy/ceritain",
    linkWeb: "https://ceritain.otakuline.id/ ",
    like: 0,
  },
  {
    id: 7,
    img: Forestapi,
    name: "Forest Api",
    user: "Rio Agung Purnomo",
    description: "Assalamualaikum! Saya Rio Agung Purnomo. Fokus menjadi Web Developer selama 3 Tahun, belajar otodidak. Saya suka belajar di WPU, sarana pembelajaran coding terbaik. Showcase projek pertama: API gratis tanpa batasan, dibuat dengan teknik scraping. Terima kasih, Pak Dhika, atas ilmu berharga Anda.",
    techStack: ["Html", "Css", "Javascript", "Tailwind CSS", "Flask"],
    imgStack: [html, css, js, tailwind, flask ],
    githubRepo: "",
    linkWeb: "https://www.forestapi.my.id/",
    like: 0,
  },
  {
    id: 8,
    img: Fresh4u,
    name: "Fresh4u",
    user: "Rizky",
    description: "Assalamualaikum! Saya Rizky, bersama Raihan dan Farrel, kami showcase proyek UKK kelas X: web fake e-commerce. Dibuat dalam 2 mingguan, peran kami beragam. Projek kompleks, pertama bagi saya dalam JavaScript/React. Masih ada bug, revisi guru. Waktu terbatas, sekitar 3-4 jam per hari. Ini projek kedua kami setelah web Quran.",
    techStack: ["React Vite", "Framer Motion", "Redux Toolkit", "Tailwind CSS"],
    imgStack: [reactjs, framer, redux, tailwind],
    githubRepo: "https://github.com/orz14/nyatet-app",
    linkWeb: "https://nyatet.orzproject.my.id/",
    like: 0,
  },
  {
    id: 9,
    img: IamRifai,
    name: "IamRifai",
    user: "Imam Rifai",
    description: "Halo pak dika dan temen - temen semua, perkenalkan nama saya Mohammad imam Rifai, saya berasal dari Indramayu Jawa Barat. Izinkan saya untuk menunjukkan hasil begadang saya :). Ini adalah website portofolio sederhana yang di buat menggunakan:",
    techStack: ["Next js 13", "Tailwind CSS"],
    imgStack: [nextjs, tailwind],
    githubRepo: "https://github.com/mohimamrifai",
    linkWeb: "https://imamrifaidev.my.id/ ",
    like: 0,
  },
  {
    id: 10,
    img: Instafam,
    name: "Instafam",
    user: "Wira",
    description: "Halo, saya Wira dari Bali. Ini showcase pertama dan proyek Next.js pertama saya. Fitur-fitur meliputi akun, like, komentar, follow, pencarian, profil, penyimpanan, post, laporan, dark mode, pesan. Harapannya mendapat masukan positif. Masih banyak kekurangan yang perlu diperbaiki",
    techStack: ["Next JS", "React JS", "Firebase", "Tailwind CSS", "Zustand"],
    imgStack: [nextjs, reactjs, firebase, tailwind, zustand],
    githubRepo: "https://github.com/wirayuda299/Instafam.git",
    linkWeb: "https://instafam.vercel.app/",
    like: 0,
  },
  {
    id: 11,
    img: Khaidar,
    name: "Khaidar",
    user: "Nitroless",
    description: "Assalamu'alaikum. Saya ingin showcase project kedua setelah ShortLink. Project kali ini adalah Website Portfolio. Terinspirasi dari video Pak Dhika. Terima kasih! 👋",
    techStack: ["Html", "Css", "Javascript"],
    imgStack: [html, css, js],
    githubRepo: "https://github.com/haidar038/haidar038.github.io",
    linkWeb: "https://khaidar.me/",
    like: 0,
  },
  {
    id: 12,
    img: Luminous,
    name: "Luminous",
    user: "Umar Jihad",
    description: "Assalamualaikum, saya Umar dari Kendari, mahasiswa informatika di UIN SUKA Yogyakarta. Saya ingin menjadi full-stack developer. Showcase ke-2: website e-commerce 'Luminous' (front-end saja). Masih dalam proses belajar back-end. Terima kasih! 👋",
    techStack: ["Next Js", "React Js"],
    imgStack: [nextjs, reactjs],
    githubRepo: "https://github.com/jihadable/myproject/tree/master/luminous",
    linkWeb: "https://luminous-2110.netlify.app/",
    like: 0,
  },
  {
    id: 13,
    img: Ngajax,
    name: "Ngajax",
    user: "zVvazoLsky",
    description: "Assalamualaikum selamat malam pak Sandhika dan teman teman, Perkenalkan nama saya tirta, disini saya mau showcase website portfolio pertama buatan saya",
    techStack: ["Html", "Css", "Javascript", "Bootstrap 5"],
    imgStack: [html, css, js, bootstrap],
    githubRepo: "https://github.com/tirtadhi/tirtadhi.github.io",
    linkWeb: "https://soerahmat69.github.io/ngajax/",
    like: 0,
  },
  {
    id: 14,
    img: Railway,
    name: "Railway",
    user: "fityannugroho",
    description: "Halo semuanya! Saya Fityan, seorang full-stack software engineer. Saya ingin membagikan proyek open API saya, idn-area, yang memberikan informasi wilayah administrasi di Indonesia. API ini menghadirkan data resmi terbaru, endpoint yang terdokumentasi, dan rangkaian tes untuk validitas data. Dikembangkan dengan NestJS, TypeScript, Prisma, dan MongoDB. Rencana mendukung berbagai jenis database. Kontribusi dan masukan selalu dihargai. Terima kasih! 🙏",
    techStack: ["Nest Js", "ORM Prisma", "Mongo DB"],
    imgStack: [nestjs, prisma, mongodb],
    githubRepo: "https://github.com/fityannugroho/idn-area",
    linkWeb: "https://idn-area.up.railway.app/",
    like: 0,
  },
  {
    id: 15,
    img: SmartCulture,
    name: "Smart Culture",
    user: "B",
    description: "Halo Pak Dhika dan teman-teman! Saya Badzlan, ingin membagikan project tim kami, Smart Culture ID. Tujuan proyek ini adalah memperkenalkan dan memfasilitasi informasi budaya provinsi di Indonesia. Kami juga juara 1 dalam I/O Fest Web Development Competition. Fitur: Konten Budaya, Pencarian, Dark Mode, Feedback*, Edit Konten*. Terima kasih! 🏆",
    techStack: ["Next Js", "Tailwind CSS"],
    imgStack: [nextjs, tailwind],
    githubRepo: "https://github.com/badzlan/smart-culture-id/",
    linkWeb: "https://smartcultureid.vercel.app/",
    like: 0,
  },
  {
    id: 16,
    img: Weekly,
    name: "Weekly Fanmade",
    user: "ikhlasdansantai",
    description: "Selamat malam! Saya Ikhsan, pertama kali showcase project. Weeekly Fanmade Website, inspirasi dari pak Dhika dan grup Twice. Proyek sederhana karena Weeekly belum punya website resmi. Awalnya iseng, tapi jadi ketagihan. Fitur: Profil Idol/Member, Sistem Voting. Terima kasih!",
    techStack: ["React Js", "Swiper Js", "Tailwind CSS"],
    imgStack: [reactjs, swiper, tailwind],
    githubRepo: "https://github.com/orz14/nyatet-app",
    linkWeb: "https://nyatet.orzproject.my.id/",
    like: 0,
  },
  {
    id: 17,
    img: Klass,
    name: "Klass",
    user: "flamrdevs",
    description: "Izin showcase proyek open-source Klass: class utility. Membantu mendesain variant-based component class. Cocok untuk TailwindCSS, UnoCSS, MasterCSS. Dukung TypeScript, styled-components. Lisensi MIT. 🚀🎨",
    techStack: ["Node Js", "PNPM", "Vite", "Vitest"],
    imgStack: [nodejs, pnpm, vite, vitest],
    githubRepo: "https://github.com/flamrdevs/klass",
    linkWeb: "https://klass.pages.dev/",
    like: 0,
  },

];
// =================== NavBarList End here ======================


