import daisyui from "daisyui";
import {
  IndoGithubers, 
  PengelolaanBuku,
  GrensaStiker,
  Qovier,
  Nyatet,
  Ceritain,
  Forestapi,
  Fresh4u,
  IamRifai,
  Instafam,
  Khaidar,
  Luminous,
  Ngajax,
  Railway,
  SmartCulture,
  Weekly,
  Pandev,
  Yazzlink,
  Klass,
  css,
  disyui,
  framer,
  html,
  js,
  laravel,
  livewire,
  mongodb,
  nextjs,
  nodejs,
  nuxtjs,
  pnpm,
  postgresql,
  prisma,
  reactjs,
  redux,
  swiper,
  vite,
  tailwind,
  vitest,
  zustand,
  firebase,
  flask,
  bootstrap,
  nestjs
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Showcase",
    link: "/showcase",
  },
  // {
  //   _id: 1002,
  //   title: "Shop",
  //   link: "/shop",
  // },
];
// =================== NavBarList End here ======================


// =================== NavBarList Start here ====================
export const ShowCaseList = [
  {
    id: 0,
    img: IndoGithubers,
    name: "IndoGitHubers!",
    user: "depa",
    description: "Halo semuanya, salam kenal 👋 perkenalkan saya depa. izin ikutan showcase project sederhana yg saya bikin 🙇‍♂️ project ini dibikin karena rasa penasaran saya soal siapa github user di indonesia yg paling banyak followers & contributions nya. sambil belajar react & biar ada hasilnya, saya coba bikin project ini dengan nama IndoGitHubers *dan ternyata rank 1 nya Pak Dhika 🥇",
    techStack: ["React JS", "Tailwind CSS"],
    imgStack: [reactjs, tailwind],
    githubRepo: "https://github.com/depapp/IndoGitHubers",
    linkWeb: "https://indogithubers.vercel.app/",
    like: 0,
  },
  {
    id: 1,
    img: PengelolaanBuku,
    name: "Pengelolaan Buku",
    user: "Kang Dappa",
    description: "Assalammulaikum pak dika dan teman teman saya mau showcase 2 project sederhana dan kecil kecilan saja btw project ini tugas akhir kelas DICODING daripada nganggur di lokal mending saya push ke production dan saya submit biar temen temen dan pak dika dapat mencoba project yang sudah saya buat ini . mohon maaf sebelumnya project ini belum responsif ( baru buat ui versi desktop )",
    techStack: ["Html", "Css", "Javascript"],
    imgStack: [html, css, js],
    githubRepo: "https://github.com/siidappa/pengelolaan-buku",
    linkWeb: "https://pengelolaan-buku.vercel.app",
    like: 0,
  },
  {
    id: 2,
    img: Qovier,
    name: "Qovier",
    user: "cholis04",
    description: "Halo Pak Dhika dan halo juga teman-teman member WPU, izinkan saya memperkenalkan personal project yang telah saya kerjakan dalam beberapa minggu ini, yang saya kasih nama Qovier. Namanya sendiri diambil dari 'Color Pairs', kemudian disingkat jadi 'Co-Pair', dan akhirnya sedikit diplesetkan menjadi Qovier. Tentang Project ini adalah sebuah online generator tool untuk berkesperimen dan menjelajahi pasangan warna. Qovier akan menghasilkan daftar pasangan warna (kombinasi dua warna) dalam bentuk solid, teks, pola, warna gradasi dan juga ilustrasi (flatline). Gas langsung cek aja",
    techStack: ["Next js", "Tailwind css", "Swipper js", "Framer motion"],
    imgStack: [nextjs, tailwind, swiper, framer],
    githubRepo: "https://github.com/PILIPSCODE/Grensa-Stiker",
    linkWeb: "https://grensa-stiker.vercel.app/",
    like: 0,
  },
  {
    id: 3,
    img: GrensaStiker,
    name: "Grensa Stiker",
    user: "Kang Error",
    description: "hallo teman teman WPU dan Pak Sandi, Saya mau memamerkan Portfolio teman saya, yang saya buat Portfolionya untuk Tambah2 Project untuk Portfolio saya",
    techStack: ["Next js", "Tailwind css", "Swipper js", "Framer motion"],
    imgStack: [nextjs, tailwind, swiper, framer],
    githubRepo: "https://github.com/PILIPSCODE/Grensa-Stiker",
    linkWeb: "https://grensa-stiker.vercel.app/",
    like: 0,
  },
    // data baru

  {
    id: 4,
    img: Pandev,
    name: "Nyatet",
    user: "zekkeN",
    description: "Assalamualaikum pak Dhika dan teman2 semua.. Saya Oriz, ini showcase project ketiga saya yaitu membuat Todo List & Note Application. Kemarin2 showcase masih pake html css php native, alhamdulillah sekarang sudah bisa menggunakan framework laravel berkat channel ini. Terimakasih banyak pak Dhika dan teman2 komunitas di discord :hehehe:Btw semua data todo list dan note di enkripsi menggunakan enkripsi bawaan laravel, jadi dapat dipastikan data yang masuk ke database akan disamarkan dengan aman. Makasih juga buat @antwa karena ikut berkontribusi pada project ini :maaf: Dengan keterbatasan ilmu yang saya miliki, saya terbuka dalam kritik dan saran dari pak Dhika dan teman2 semua. Fitur : Login & Register Login with GitHub / Google Reset Password (dikirim ke email) Todo List Note (bisa dikunci) Enkripsi Laravel menggunakan OpenSSL untuk menyediakan enkripsi AES-256 dan AES-128 (contoh hasil enkripsinya ada di readme)",
    techStack: ["Laravel 10", "Tailwind CSS", "Livewire", "Daisy UI"],
    imgStack: [laravel, tailwind, livewire, disyui],
    githubRepo: "https://github.com/orz14/nyatet-app",
    linkWeb: "https://nyatet.orzproject.my.id/",
    like: 0,
  },
  {
    id: 5,
    img: Yazzlink,
    name: "Yazzlink",
    user: "yazz",
    description: "Assalamualaikum pak Dhika dan semuanyaa Kenalin saya Muhammad Yazid Akbar dan ini adalah showcase pertama saya Sekarang saya sedang belajar firebase, dan mengimplementasikannya ke project website yg saya buat ini. Saya membuat website yang mirip seperti linktr.ee atau bagi yg belum tau itu adalah website untuk membuat website yg menampilkan button link, contohnya link semua akun social media kalian. Tech Stack yg digunakan : Next js@latest Firebase Tailwind CSS Ant Design Fitur : Add Link / Header Upload Photo Profile Edit Background Color Upload Background Image Edit button color, button font color, font color Edit username (untuk akhiran url website yg kmu buat) Tracking Visitor and Tracking Button Link Realtime",
    techStack: ["Next js", "Firebase", "Tailwind CSS"],
    imgStack: [nextjs, firebase, livewire, disyui],
    githubRepo: "https://github.com/yazz803/linker_sosmed",
    linkWeb: "https://yazzlink.vercel.app/",
    like: 0,
  },
  {
    id: 6,
    img: Ceritain,
    name: "Ceritain",
    user: "CicakUngu",
    description: "Assalamualaikum pak Dhika dan teman-teman semua. Perkenalkan saya rijal, dan ini adalah showcase ke dua saya. Di showcase kali ini saya membuat sebuah website yang bernama ceritain. Di website ini kalian bisa menuliskan hal-hal yang ingin kalian ceritakan seperti menulis keluh kesah, curhatan kalian, dan lain sebagainya. Oh iya, website ini masih dalam pengembangan, jadi mungkin saja kalian akan menemukan beberapa bug ketika membuka website ini.",
    techStack: ["Nuxt JS", "Tailwind CSS", "PostgreSQL",],
    imgStack: [nuxtjs, tailwind, postgresql, nodejs],
    githubRepo: "https://github.com/euxzy/ceritain",
    linkWeb: "https://ceritain.otakuline.id/ ",
    like: 0,
  },
  {
    id: 7,
    img: Forestapi,
    name: "Forest Api",
    user: "Rio Agung Purnomo",
    description: "Assalamualaikum Halo selamat malam Pak Dhika dan temen temen WPU lainnya, perkenalkan nama saya Rio Agung Purnomo dan saya ingin fokus menjadi Web Developer dengan belajar otodidak selama 3 Tahun dan saya juga sangat suka belajar di WPU, channel favorit saya dan sangat disarankan untuk belajar coding atau bagaimana menjadi Web Developer pembelajaran yang jelas dan sangat mudah untuk dimengerti, sebelumnya Terimakasih untuk Pak Dhika telah memberikan ilmu yang sangat penting untuk seseorang yang ingin mempunyai skill dan prestasi untuk masa depan. Ini pertama kali nya saya showcase projek, projek yang saya buat ini seperti penyedia API dan saya sediakan gratis tanpa apikey ataupun limit yang bisa digunakan kapan saja dan dimana saja dan saya membuat API tersebut dengan menggunakan teknik scraping.",
    techStack: ["Html", "Css", "Javascript", "Tailwind CSS", "Flask"],
    imgStack: [html, css, js, tailwind, flask ],
    githubRepo: "",
    linkWeb: "https://www.forestapi.my.id/",
    like: 0,
  },
  {
    id: 8,
    img: Fresh4u,
    name: "Fresh4u",
    user: "Rizky",
    description: "Assalamualaikum Pak Dhika, saya rizky dan kawan kawan raihan, farrel mau showcase project UKK kelas X, jadi saya buat web fake e commerce jadi kalo di refresh ke reset lagi hehehe, gambar2 product di web nya aga burem kita kesusahan cari gambar2 jadi sedapetnya aja, kira kira pembuatan webnya 2 mingguan lebih, dan role role nya kalo saya yang megang js/react kalo si raihan html/css dan si farrel figma/design, projectnya juga belum sempurna bgt, buat saya yang megang js ini merupakan projek pertama kali yang luamayan kompleks bagi saya mulai dari pembuatan fitur add to cart, wishlist dll jadi kalo ada error mohon di maklumi heheh , pasti nnti juga kena revisi dari guru hahaha, waktu pengeerjaannya juga paling 3-4 jam perhari karna emang sekitar segitu kita bisa megang laptop di pondok , belum lagi ada tugas pelajaran lain, ini projek kedua saya dan kawan2 , sebelumnya saya kirim project web quran. minta koreksinya dong pak dika hehehe",
    techStack: ["React Vite", "Framer Motion", "Redux Toolkit", "Tailwind CSS"],
    imgStack: [reactjs, framer, redux, tailwind],
    githubRepo: "https://github.com/orz14/nyatet-app",
    linkWeb: "https://nyatet.orzproject.my.id/",
    like: 0,
  },
  {
    id: 9,
    img: IamRifai,
    name: "IamRifai",
    user: "Imam Rifai",
    description: "Halo pak dika dan temen - temen semua, perkenalkan nama saya Mohammad imam Rifai, saya berasal dari Indramayu Jawa Barat. Izinkan saya untuk menunjukkan hasil begadang saya :). Ini adalah website portofolio sederhana yang di buat menggunakan:",
    techStack: ["Next js 13", "Tailwind CSS"],
    imgStack: [nextjs, tailwind],
    githubRepo: "https://github.com/mohimamrifai",
    linkWeb: "https://imamrifaidev.my.id/ ",
    like: 0,
  },
  {
    id: 10,
    img: Instafam,
    name: "Instafam",
    user: "Wira",
    description: "Halo semuanya, Perkenalkan nama saya Wira dari Bali, Ini adalah showcase pertama dan juga project Nextjs pertama saya, yang tentunya masih banyak kekurangan. Dengan harapan memperlihatkan project ini disini ada masukan yang positif dan membangun. Feature; Create an account Login Log out Like and comment on posts Follow and unFollow other users Search for users by username or name View your profile Crop photo before upload View other users' profiles View your feed Save posts to your profile View your saved posts Create a post View your posts Delete your posts Simple detection of nudity in images while create a post Navigate to spesific post, Copy post link Share post Responsive design Update your posts Report posts Dark mode toggler Send messages to other users",
    techStack: ["Next JS", "React JS", "Firebase", "Tailwind CSS", "Zustand"],
    imgStack: [nextjs, reactjs, firebase, tailwind, zustand],
    githubRepo: "https://github.com/wirayuda299/Instafam.git",
    linkWeb: "https://instafam.vercel.app/",
    like: 0,
  },
  {
    id: 11,
    img: Khaidar,
    name: "Khaidar",
    user: "Nitroless",
    description: "Assalamu'alaikum.. Halo Pak Dhika, Halo Sobat WPU Ini adalah showcase project ke-2 saya setelah beberapa waktu lalu project saya yang pertama (ShortLink) telah direview oleh Pak Dhika dan Sobat WPU sekalian. Kali ini project yang ingin saya showcase sudah tidak lagi sederhana. Project ini adalah sebuah Website Portfolio yang kebetulan ide pembuatannya terinspirasi dari video Pak Dhika tentang Website Portfolio.",
    techStack: ["Html", "Css", "Javascript"],
    imgStack: [html, css, js],
    githubRepo: "https://github.com/haidar038/haidar038.github.io",
    linkWeb: "https://khaidar.me/",
    like: 0,
  },
  {
    id: 12,
    img: Luminous,
    name: "Luminous",
    user: "Umar Jihad",
    description: "Assalamualaikum warahmatullahi wabarakatuh. Perkenalkan, Saya Umar dari Kendari. Saya seorang mahasiswa informatika UIN SUKA Yogyakrata. Saya ingin menjadi full stack developer. Ini showcase ke-2 Saya yaitu website e-commerce bernama \"Luminous\" yang menjual barang-barang kebutuhan rumah tangga. Disclaimer: project ini hanya dari sisi front-end nya saja. Saya masih dalam proses belajar back-end",
    techStack: ["Next Js", "React Js"],
    imgStack: [nextjs, reactjs],
    githubRepo: "https://github.com/jihadable/myproject/tree/master/luminous",
    linkWeb: "https://luminous-2110.netlify.app/",
    like: 0,
  },
  {
    id: 13,
    img: Ngajax,
    name: "Ngajax",
    user: "zVvazoLsky",
    description: "Assalamualaikum selamat malam pak Sandhika dan teman teman, Perkenalkan nama saya tirta, disini saya mau showcase website portfolio pertama buatan saya",
    techStack: ["Html", "Css", "Javascript", "Bootstrap 5"],
    imgStack: [html, css, js, bootstrap],
    githubRepo: "https://github.com/tirtadhi/tirtadhi.github.io",
    linkWeb: "https://soerahmat69.github.io/ngajax/",
    like: 0,
  },
  {
    id: 14,
    img: Railway,
    name: "Railway",
    user: "fityannugroho",
    description: "Halo Pak Dhika dan rekan-rekan semuanya! Perkenalkan, saya Fityan, full-stack software engineer. Saya ingin membagikan project open API yang saya kembangkan, yaitu: idn-area, API yang menyediakan informasi wilayah administrasi di Indonesia mulai dari tingkat provinsi, kabupaten/kota, kecamatan, hingga desa/kelurahan. Fitur-Fitur Menggunakan data resmi terbaru yang dikeluarkan oleh pemerintah. API endpoint yang terdokumentasi dengan baik dan mudah digunakan untuk mengambil data provinsi, kabupaten/kota, kecamatan, dan desa/kelurahan. Menggunakan rangkaian tes untuk memastikan validitas sumber data dan juga data keluaran dari setiap endpoint. API playground untuk mencoba endpoint dan memeriksa respon (lihat /docs endpoint). API ini dikembangkan menggunakan framework NestJS dengan bahasa pemrograman TypeScript, ORM Prisma dan database MongoDB. Kedepannya berencana untuk mendukung jenis database lain seperti MySQL, PostgreSQL, dll Jika rekan-rekan menemukan bug, atau ingin ada fitur baru, atau peningkatan-peningkatan lainnya, jangan sungkan untuk berkontribusi ya. Terima kasih semuanya 🙏",
    techStack: ["Nest Js", "ORM Prisma", "Mongo DB"],
    imgStack: [nestjs, prisma, mongodb],
    githubRepo: "https://github.com/fityannugroho/idn-area",
    linkWeb: "https://idn-area.up.railway.app/",
    like: 0,
  },
  {
    id: 15,
    img: SmartCulture,
    name: "Smart Culture",
    user: "B",
    description: "Halo Pak Dhika dan Teman-teman semua! Perkenalkan saya Badzlan, Saya ingin membagikan project tim saya bersama 2 teman saya lainnya yakni Ridwan dan Abiyyu. Project ini bernama Smart Culture ID. Tujuan dari project ini adalah untuk memperkenalkan serta memfasilitasi Informasi tentang Budaya Provinsi yang ada di Indonesia. Selain itu, project ini juga mendapatkan perhargaan sebagai Juara 1 pada I/O Fest Web Development Competition yang diadakan oleh BEM FTI Universitas Tarumanagara pada 25 Mei 2023 kemarin. Fitur - fitur : • Konten Budaya • Search / Pencarian • Dark Mode • Feedback* • Edit Konten*",
    techStack: ["Next Js", "Tailwind CSS"],
    imgStack: [nextjs, tailwind],
    githubRepo: "https://github.com/badzlan/smart-culture-id/",
    linkWeb: "https://smartcultureid.vercel.app/",
    like: 0,
  },
  {
    id: 16,
    img: Weekly,
    name: "Weekly Fanmade",
    user: "ikhlasdansantai",
    description: "Selamat malam pak Dhika dan teman teman wpu lainnya, perkenalkan nama saya ikhsan, ini pertama kalinya saya showcase project, project yang sangat sederhana ini adalah (weeekly fanmade website), terinpirasi dari pak Dhika yang suka sama group twice, sampai bikin twice survey from di freecodecamp. Awal nya sih iseng karena suka sama musiknya yang After School, akhirnya riset untuk cari official website dari group Weeekly ini, ternyata belum punya website resminya, akhirnya saya coba untuk bikin versi saya sendiri, sebenarnya project ini adalah project yang saya kerjakan di bulan ramadhan, tapi sekarang saya jadi ketagihan buat ikutan showcase, hehehe. Fitur Profil Idol/Member: User dapat mengklik gambar setiap idol/member, yang akan menampilkan profil singkat tentang idol/member yang dipilih. Sistem Voting: user dapat memilih idol favorit nya dengan mengklik tombol Vote yang terletak di bagian #Vote Your Bias. Setiap vote/klik akan menambahkan 1 suara untuk idol yang dipilih.",
    techStack: ["React Js", "Swiper Js", "Tailwind CSS"],
    imgStack: [reactjs, swiper, tailwind],
    githubRepo: "https://github.com/orz14/nyatet-app",
    linkWeb: "https://nyatet.orzproject.my.id/",
    like: 0,
  },
  {
    id: 17,
    img: Klass,
    name: "Klass",
    user: "flamrdevs",
    description: "Halo, Pak Dhika dan teman-teman semuanya, izin showcase open-source javascript project. 🚀 Introduction Klass : class variant utility, adalah sebuah javascript utility library untuk membuat dan mendesain variants based component class secara terstruktur. Klass terinspirasi dari cva, stitches, vanilla-extract dan tailwind-variants. Klass akan sangat cocok jika digunakan dengan utility-first css framework seperti TailwindCSS, UnoCSS dan MasterCSS. Klass berada dibawah lisensi MIT. 🎨 Feature framework agnostic base, variants, default variants, compound variants, responsive variants group and slots first class typescript support styled-component like (preact,react,solid) - ex : klassed(\"div\", /* options */) polymorphic components (preact,react,solid) - as prop",
    techStack: ["Node Js", "PNPM", "Vite", "Vitest"],
    imgStack: [nodejs, pnpm, vite, vitest],
    githubRepo: "https://github.com/flamrdevs/klass",
    linkWeb: "https://klass.pages.dev/",
    like: 0,
  },

];
// =================== NavBarList End here ======================


